name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/markdown-link-check
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
  create-pdf-html:
    needs: validate-markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/markdown-to-pdf-and-html
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: 'sheets'
          output_dir: generated-files
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: generated-files
          path: generated-files
